services:
  mysql:
    image: mysql:8.4.4
    volumes:
      - ./data/legacy-db:/var/lib/mysql
    ports:
      - "3316:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: legacy
  postgresql:
    image: postgres:16.8
    volumes:
      - ./data/advanced-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
