services:
  mysql:
    image: mysql:8.4.4
    volumes:
      - ./data/legacy-db:/var/lib/mysql
    ports:
      - "3316:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: legacy
  postgresql:
    image: postgres:16.8
    volumes:
      - ./data/advanced-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PW}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
  kafka:
    image: bitnami/kafka:3.4.1
    ports:
      - '9194:9194'
    restart: always
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9193
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9193,EXTERNAL://:9194
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9192,EXTERNAL://localhost:9194
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "7081:8080"
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9192